### ISSUE TITLE
SyntaxError in geturl on line 53

### ISSUE THREAD

**Issue by derblub** [uams/geturl#10]
Getting a syntax error:

```
$ geturl .vimrc
   File "/usr/local/bin/geturl", line 53
   print "usage: geturl <filename>"
                                  ^
   SyntaxError: invalid syntax
```

on Archlinux

**Comment by Gonzih** [comment]
Same issue on ArchLinux

**Comment by uams** [comment]
Interesting. I presume it doesn't like the greater than '>'? Easy fix seems like changing it to "geturl path/to/file" or just "geturl filepath"

**Comment by molecula21** [comment]
Doesnt work for me too. Applying the changes mentioned above dont fix the problem at all. I am also under Arch. Maybee it is because we use python3 or something related to python version... I am looking forward to use this script :)

**Comment by uams** [comment]
#15 should have fixed this, largely replacing the stub of a help with argparse. Thanks.
