### ISSUE TITLE
Input via stdin.

### ISSUE THREAD

**Issue by xeago** [uams/geturl#19]
Please allow input via stdin. This way arbitrary commands can be piped into geturl and don't have to be saved to file first. Would also be handy for quickly sending over your clipboard to someone: `pbpaste | geturl`.

Cheers!

**Comment by uams** [comment]
That would be super useful. Looking forward to a pull request? :D

**Comment by xeago** [comment]
I don't know (much) python, I'll see if I can code something up this
weekend. :)
