### ISSUE TITLE
5000 file limit

### ISSUE THREAD

**Issue by dmd** [uams/geturl#2]
Suggestions:
- expiry
- auto-removing the oldest file when you hit the 5000 limit

**Comment by uams** [comment]
It's something like 5000/files/month. If someone hits this, we can talk about it more as there are ways of deleting files (not sure how it counts against your quota) Otherwise, closing?

**Comment by dmd** [comment]
Oh. 5000/month? I thought it was 5000 total. If it's per month, then, yeah, don't worry!
