### ISSUE TITLE
Filenames with spaces fail on upload.

### ISSUE THREAD

**Issue by wink** [uams/geturl#3]
Uploading a file with a space in its filename returns an error after upload is complete:

$ geturl ~/Documents/insurance\ claim.txt 

Uploading the file to Filepicker.io...
###### ################################################################## 100.0%

curl: (6) Could not resolve host: claim.txt; nodename nor servname provided, or not known
Traceback (most recent call last):
  File "/usr/local/bin/geturl", line 56, in <module>
    {"filename": sys.argv[1], "apikey": APIKEY, "fpurl": FPURL}, shell=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 544, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'curl --progress-bar -F "fileUpload=@/Users/wink/Documents/insurance claim.txt" -F "apikey=Au2fZ0IXMQguEemJ1bb4_z" https://www.filepicker.io/api/path/storage//Users/wink/Documents/insurance claim.txt' returned non-zero exit status 6

Awesome tool, by the way. +1 on a brew install.

**Comment by yonson2** [comment]
I also get errors when uploading files with non-alfanumeric characters, such as `[foo]__bar.txt`.

**Comment by uams** [comment]
Yeah. I should be url encoding.

**Comment by dideler** [comment]
First reference (4c50578) is just this fix on the master branch. Second reference (308e19c) is from a branch where I also made other changes.
