### ISSUE TITLE
ImportError: No module named check_output

### ISSUE THREAD

**Issue by tomw1808** [uams/geturl#9]
root@lamp /home/www# geturl extjs.tar.gz
Traceback (most recent call last):
  File "/usr/local/bin/geturl", line 7, in <module>
    from check_output import check_output
ImportError: No module named check_output

Am I doing something wrong? I'm missing some dependencies?

**Comment by tomw1808** [comment]
sorry, my bad, just copied the link in your description ...

**Comment by alessioalex** [comment]
So, where to add this.. ? The description doesn't mention anything about where I should put this file.

**Comment by timdavies** [comment]
@alessioalex Try putting it in /usr/lib/python2.6/

I think that check_output.py should be added into the geturl file as it's small and the benefits of splitting up and simplifying the code are outweighed by the inconvenience of setting up the module in the python path.

I have done this on my fork (https://github.com/dotty/geturl) and it makes deployment of geturl a lot faster.
